version: 2.1
jobs:
  build:
    docker:
      # the primary container, where your job's commands are run
      - image: rust:1
    steps:
      # check out the code in the project directory
      - checkout
      - run:
          name: Run tests
          command: |
            make test
